// tests/e2e-lifecycle.test.js
//
// FIX review cuối (finding 9d): KHÔNG có test nào đi trọn vòng đời — mà mọi
// finding của review cuối đều nằm ở KHE GIỮA CÁC LỆNH (gate ↔ review-record ↔
// approve ↔ advance ↔ hook), đúng chỗ không test nào bước qua. Test này chạy
// nguyên vòng: init → viết artifact → T1 → T2 → approve → stage kế tiếp →
// hoàn tất, và khẳng định STATE.md cuối cùng.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { writeFileSync, readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { readState } from '../lib/state.js'
import { makeRoot, run, runSplit, passT1Prd, verdictFile, TESTPLAN } from './helpers.js'

test('vòng đời đầy đủ: init → artifact → T1 → T2 → approve → stage kế tiếp → hoàn tất', () => {
  const root = makeRoot()
  const dir = join(root, 'features/demo')

  // 1. init
  assert.equal(run(['init', 'demo', '--size', 'S', '--root', root]).code, 0)
  assert.ok(existsSync(join(dir, 'pipeline.json')))

  // 2. status trỏ vào stage đầu tiên, chưa chạy
  const s0 = run(['status', 'demo', '--root', root])
  assert.equal(s0.code, 0)
  assert.match(s0.out, /stage kế tiếp : 10-prd/)
  assert.match(s0.out, /hành động {5}: run/)

  // 3. advance in chỉ thị, có nêu tier bắt buộc
  const a0 = run(['advance', 'demo', '--root', root])
  assert.match(a0.out, /CHỈ THỊ CHO STAGE 10-prd/)
  assert.match(a0.out, /Tier bắt buộc : t1, t2/)

  // 4. viết artifact rồi chạy T1 THẬT
  const g1 = passT1Prd(root)
  assert.match(g1.out, /RESULT: PASS \(t1\)/)
  assert.match(g1.out, /CHƯA done/)
  const afterT1 = readState(dir).stages['10-prd']
  assert.equal(afterT1.status, 'in_progress')
  assert.deepEqual(afterT1.outstanding, ['t2'])

  // 4b. Stop hook giữ phiên lại khi còn tier chưa chạy
  assert.equal(runSplit(['guard-stop', '--root', root]).code, 2)

  // 4c. approve bị từ chối khi stage chưa done — human gate không cứu được T2
  assert.equal(run(['approve', 'demo', '10-prd', '--root', root]).code, 1)

  // 5. T2: prompt rồi record verdict sạch
  assert.equal(run(['review-prompt', 'demo', '10-prd', '--root', root]).code, 0)
  const v1 = verdictFile(root, 'demo', '10-prd', [
    { criterion: 'AC đo được', verdict: 'pass', severity: 'low', evidence: 'AC-1-1 EARS', fix: '' },
  ])
  const rr1 = run(['review-record', 'demo', '10-prd', '--verdict', v1, '--root', root])
  assert.equal(rr1.code, 0)
  assert.equal(readState(dir).stages['10-prd'].status, 'done')

  // 6. human gate #1
  const s1 = run(['status', 'demo', '--root', root])
  assert.match(s1.out, /await-human/)
  assert.equal(run(['approve', 'demo', '10-prd', '--root', root]).code, 0)

  // 7. stage kế tiếp
  const a1 = run(['advance', 'demo', '--root', root])
  assert.match(a1.out, /CHỈ THỊ CHO STAGE 40-testplan/)
  assert.match(a1.out, /Tier bắt buộc : t1, t2/)

  writeFileSync(join(dir, '40-testplan.md'), TESTPLAN)
  const g2 = run(['gate', 'demo', '40-testplan', '--root', root])
  assert.equal(g2.code, 0, g2.out)
  assert.match(g2.out, /CHƯA done/)
  const v2 = verdictFile(root, 'demo', '40-testplan', [])
  assert.equal(run(['review-record', 'demo', '40-testplan', '--verdict', v2, '--root', root]).code, 0)

  // 8. hoàn tất
  const s2 = run(['status', 'demo', '--root', root])
  assert.equal(s2.code, 0)
  assert.match(s2.out, /mọi stage đã xong/)
  assert.equal(run(['advance', 'demo', '--root', root]).code, 0)
  // không còn stage nào failed/in_progress → Stop hook cho dừng
  assert.equal(runSplit(['guard-stop', '--root', root]).code, 0)

  // 9. STATE.md cuối cùng — dữ kiện, không phải lời khai
  const txt = readFileSync(join(dir, 'STATE.md'), 'utf8')
  assert.match(txt, /GENERATED BY pp — DO NOT EDIT/)
  assert.match(txt, /\| 10-prd \| done \| 0 \| pass \| approved \|/)
  assert.match(txt, /\| 40-testplan \| done \| 0 \| pass \| - \|/)
  assert.doesNotMatch(txt, /in_progress/)

  const st = readState(dir).stages
  for (const id of ['10-prd', '40-testplan']) {
    assert.equal(st[id].status, 'done')
    assert.equal(st[id].gate, 'pass')
    assert.equal(st[id].attempts, 0)
    assert.equal(st[id].tiers.t1.result, 'pass')
    assert.equal(st[id].tiers.t2.result, 'pass')
    assert.equal(typeof st[id].inputs_hash, 'string')
    assert.equal(st[id].outstanding, undefined)
    // Bốn file evidence riêng biệt, không file nào bị ghi đè
    for (const tier of ['t1', 't2']) {
      const log = join(dir, '.evidence', `${id}.${tier}.log`)
      assert.ok(existsSync(log), `thiếu ${log}`)
      assert.match(readFileSync(log, 'utf8'), new RegExp(`RESULT: PASS \\(${tier}\\)`))
    }
  }
  assert.equal(st['10-prd'].human, 'approved')
})

// Cùng vòng đời đó nhưng gate đỏ: hệ phải DỪNG, không trôi sang stage sau.
test('vòng đời với T1 đỏ: stage không done, stage sau không bao giờ tới lượt', () => {
  const root = makeRoot()
  const dir = join(root, 'features/demo')
  run(['init', 'demo', '--size', 'S', '--root', root])

  writeFileSync(join(dir, '10-questions.md'), 'Q1: hỏi gì đó?\nA: trả lời\n')
  writeFileSync(join(dir, '10-prd.md'), '# PRD\n\n## User stories\n\nTBD\n')
  const g = run(['gate', 'demo', '10-prd', '--root', root])
  assert.equal(g.code, 1)

  const st = readState(dir).stages['10-prd']
  assert.equal(st.status, 'failed')
  assert.equal(st.attempts, 1)
  assert.equal(st.tiers.t1.result, 'fail')

  // T2 không được chạy, approve không được, advance vẫn quay lại 10-prd
  const v = verdictFile(root, 'demo', '10-prd', [])
  assert.equal(run(['review-record', 'demo', '10-prd', '--verdict', v, '--root', root]).code, 1)
  assert.equal(run(['approve', 'demo', '10-prd', '--root', root]).code, 1)
  assert.match(run(['advance', 'demo', '--root', root]).out, /10-prd/)
  assert.equal(runSplit(['guard-stop', '--root', root]).code, 2)
})
