import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { join } from 'node:path'

const FILE = 'STATE.md'
const OPEN = '<!-- pp:state'
const CLOSE = '-->'

export function readState(featureDir) {
  const file = join(featureDir, FILE)
  if (!existsSync(file)) return { feature: null, current: null, stages: {} }
  const txt = readFileSync(file, 'utf8')
  const i = txt.indexOf(OPEN)
  if (i === -1) throw new Error(`${file}: thiếu khối ${OPEN} — file có thể đã bị sửa tay`)
  const j = txt.indexOf(CLOSE, i)
  const json = txt.slice(i + OPEN.length, j).trim()
  return JSON.parse(json)
}

function renderTable(state) {
  const head = '| stage | status | attempts | gate | human |\n|---|---|---|---|---|'
  const rows = Object.entries(state.stages).map(
    ([id, s]) =>
      `| ${id} | ${s.status ?? 'pending'} | ${s.attempts ?? 0} | ${s.gate ?? '-'} | ${s.human ?? '-'} |`,
  )
  return [head, ...rows].join('\n')
}

export function writeState(featureDir, state) {
  let json = JSON.stringify({ ...state, updated: state.updated ?? new Date().toISOString() }, null, 2)
  // Escape --> to prevent premature delimiter closure
  json = json.replace(/-->/g, '--\\u003e')
  const body = `<!-- GENERATED BY pp — DO NOT EDIT (PreToolUse hook chặn agent ghi file này) -->
# STATE — ${state.feature ?? ''}

current: **${state.current ?? '(hoàn tất)'}** · updated: ${state.updated ?? new Date().toISOString()}

${renderTable(state)}

${OPEN}
${json}
${CLOSE}
`
  writeFileSync(join(featureDir, FILE), body)
}

export function hashInputs(featureDir, inputs) {
  const h = createHash('sha256')
  for (const inp of inputs) {
    const p = join(featureDir, inp.path)
    if (!existsSync(p)) {
      if (inp.optional) continue
      throw new Error(`input bắt buộc không tồn tại: ${inp.path}`)
    }
    h.update(inp.path).update('\0').update(readFileSync(p))
  }
  return h.digest('hex').slice(0, 6)
}

// R1 (review cuối) — MỘT KẾT QUẢ TIER CHỈ CÓ GIÁ TRỊ VỚI ĐÚNG ARTIFACT NÓ
// ĐÃ CHẤM. `isStale` chỉ băm INPUT thượng nguồn của stage, không bao giờ băm
// chính OUTPUT của nó — nên một stage đã `done` hợp lệ vẫn giữ nguyên `done`
// sau khi artifact bị viết lại thành nội dung khác hẳn (quan sát được: PRD
// bị sửa thành "bỏ hoàn toàn kiểm tra phân quyền" mà `pp gate` vẫn in
// "✓ done"). T2 không chạy lại; phán quyết cũ được ghi cho BẢN TRƯỚC.
//
// Dùng lại CHÍNH cách băm của `hashInputs` (sha256 trên path + nội dung, cắt
// 6 hex) — một cách băm duy nhất trong toàn hệ, không đẻ ra cách thứ hai.
export function hashArtifact(featureDir, path) {
  try {
    return hashInputs(featureDir, [{ path, optional: false }])
  } catch {
    // Artifact được khai báo nhưng không còn trên đĩa: không băm được, và
    // cũng không được coi là "khớp" với bất kỳ hash nào đã ghi.
    return 'missing'
  }
}

export function isStale(featureDir, config, state, stageId) {
  const st = state.stages?.[stageId]
  if (!st || st.status !== 'done') return false
  // Overridden stages are never stale (override is an explicit human decision)
  if (st.overridden) return false
  // If no hash recorded, stage is stale (unknown provenance — re-gate)
  if (!st.inputs_hash) return true
  return hashInputs(featureDir, config.stages[stageId].inputs) !== st.inputs_hash
}
