import { readFileSync, writeFileSync, existsSync, renameSync, rmSync, mkdirSync, rmdirSync, statSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { join } from 'node:path'

const FILE = 'STATE.md'
const OPEN = '<!-- pp:state'
const CLOSE = '-->'

// C1/C6 — MỘT STATE.md KHÔNG ĐỌC ĐƯỢC TỪNG CHẾT BẰNG LỖI PARSER THÔ.
// Tái lập được: cắt STATE.md giữa khối JSON (đúng hình dạng một lần ghi bị giết
// nửa chừng, trước khi writeState thành atomic) rồi chạy bất kỳ lệnh nào —
//
//   pp status demo → "pp: Expected double-quoted property name in JSON at position 23"
//
// Không tên file, không nói vì sao, không nói làm gì tiếp — người dùng bế tắc ở
// đúng khoảnh khắc dữ liệu của họ vừa hỏng. Mọi đường hỏng phải nói: file nào,
// hỏng kiểu gì, và hai lối ra thật (git checkout nếu được track; không thì xoá
// file — pp coi mọi stage là chưa chạy và bắt gate/review/approve lại từ đầu,
// vì bản ghi tier trong state là một nửa của bằng chứng, evidence log là nửa kia).
function corrupt(file, why) {
  return new Error(
    `${file}: ${why} — STATE.md hỏng (bị sửa tay, hoặc một lần ghi cũ bị giết nửa chừng).\n` +
    `Khôi phục: \`git checkout -- ${file}\` nếu file có trong git; không thì xoá nó — ` +
    'pp sẽ coi mọi stage là chưa chạy và yêu cầu gate/review/approve lại từ đầu.',
  )
}

export function readState(featureDir) {
  const file = join(featureDir, FILE)
  if (!existsSync(file)) return { feature: null, current: null, stages: {} }
  const txt = readFileSync(file, 'utf8')
  const i = txt.indexOf(OPEN)
  if (i === -1) throw corrupt(file, `thiếu khối ${OPEN}`)
  const j = txt.indexOf(CLOSE, i)
  // indexOf = -1 mà cứ thế slice(i, -1) là âm thầm cắt mất ký tự cuối rồi đổ
  // lỗi cho JSON.parse — khối không đóng là một sự việc, nói đúng tên nó.
  if (j === -1) throw corrupt(file, `khối ${OPEN} không có ${CLOSE} đóng (file bị cắt cụt?)`)
  const json = txt.slice(i + OPEN.length, j).trim()
  try {
    return JSON.parse(json)
  } catch (e) {
    throw corrupt(file, `khối pp:state không phải JSON hợp lệ (${e.message})`)
  }
}

function renderTable(state) {
  const head = '| stage | status | attempts | gate | human |\n|---|---|---|---|---|'
  const rows = Object.entries(state.stages).map(
    ([id, s]) =>
      `| ${id} | ${s.status ?? 'pending'} | ${s.attempts ?? 0} | ${s.gate ?? '-'} | ${s.human ?? '-'} |`,
  )
  return [head, ...rows].join('\n')
}

export function writeState(featureDir, state) {
  // BOOTSTRAP (chạy thật feature đầu tiên) — `updated` TỪNG ĐÓNG BĂNG Ở LẦN GHI
  // ĐẦU TIÊN VÀ KHÔNG BAO GIỜ ĐỔI.
  // Bản cũ viết `state.updated ?? new Date()`. `readState` trả về nguyên cả
  // `updated` cũ, nên mọi lần ghi sau đó đều thấy trường này ĐÃ có và giữ lại giá
  // trị của `pp init`. Quan sát được trên feature `archive-command`: STATE.md ghi
  // `updated: 08:12:06` (lúc init) trong khi lần ghi thật cuối cùng là 08:23:14 —
  // sai 11 phút, ở đúng cái trường mà công việc duy nhất của nó là nói "file này
  // được ghi lúc nào". Ai đọc STATE.md để biết pipeline có đang chạy hay không sẽ
  // bị nó nói dối.
  //
  // Tính MỘT LẦN rồi dùng cho cả JSON lẫn dòng người đọc: bản cũ gọi `new Date()`
  // hai lần riêng biệt, nên hai chỗ có thể lệch nhau ở lần ghi đầu.
  const updated = new Date().toISOString()
  let json = JSON.stringify({ ...state, updated }, null, 2)
  // Escape --> to prevent premature delimiter closure
  json = json.replace(/-->/g, '--\\u003e')
  // A2 — BANNER TỪNG ĐẢM BẢO QUÁ ĐIỀU HỆ THỐNG LÀM ĐƯỢC.
  // Bản cũ ghi "(PreToolUse hook chặn agent ghi file này)" như một dữ kiện. Hai
  // cách nó sai: (1) hook chỉ chạy nếu một settings.json nào đó đăng ký nó — trên
  // một clone mới thì không, và banner vẫn in y nguyên (xem `pp doctor`); (2) kể cả
  // khi đã bật, một chuỗi Bash đủ vòng vo vẫn lách được lớp heuristic ở
  // lib/commands/guard.js. Nói đúng mức: đây là file do `pp` sinh, sửa tay là sai
  // — thay vì tuyên bố một cơ chế đang canh nó.
  const body = `<!-- GENERATED BY pp — DO NOT EDIT. Chỉ \`pp\` được ghi file này; sửa tay là làm giả evidence. -->
<!-- Kiểm tầng chặn có đang bật: \`pp doctor\`. -->
# STATE — ${state.feature ?? ''}

current: **${state.current ?? '(hoàn tất)'}** · updated: ${updated}

${renderTable(state)}

${OPEN}
${json}
${CLOSE}
`
  // C1 — GHI THẲNG LÊN STATE.md LÀ ĐẶT CƯỢC VÀO VIỆC PROCESS KHÔNG BAO GIỜ CHẾT
  // GIỮA CHỪNG. `writeFileSync` không atomic: bị giết giữa lúc ghi để lại một
  // file cụt, `readState` từ chối nó, và MỌI lệnh cần state đều chết theo —
  // đúng file mà cả hệ thống dùng làm sổ cái. Ghi ra file tạm CÙNG THƯ MỤC
  // (rename chỉ atomic trong cùng filesystem) rồi rename đè: crash trước rename
  // thì STATE.md cũ còn nguyên, crash sau rename thì bản mới đã trọn vẹn —
  // không tồn tại thời điểm nào file dở dang mang tên STATE.md.
  const tmp = join(featureDir, `.${FILE}.tmp-${process.pid}`)
  try {
    writeFileSync(tmp, body)
    renameSync(tmp, join(featureDir, FILE))
  } catch (err) {
    // Ghi tạm thất bại (đĩa đầy, quyền): đừng bỏ rác lại — STATE.md cũ vẫn nguyên.
    rmSync(tmp, { force: true })
    throw err
  }
}

// C1 — HAI LỆNH `pp` CHẠY SONG SONG TRÊN CÙNG FEATURE LÀ READ-MODIFY-WRITE
// KHÔNG KHOÁ: cả hai đọc cùng một STATE.md, mỗi bên ghi đè kết luận của bên kia
// (lost update). `recordTierRun` và `mergeFreshStage` đọc-tươi-tại-chỗ đã thu
// hẹp cửa sổ đua xuống mili-giây nhưng không đóng nó. Khoá bằng `mkdirSync`
// KHÔNG recursive — tạo thư mục là thao tác atomic ở tầng filesystem, tồn tại
// là EEXIST, không có "kiểm rồi mới tạo" để mà đua.
//
// Khoá stale: một process bị giết giữa chừng để lại thư mục khoá mãi mãi, và
// mọi lệnh sau sẽ treo rồi lỗi — nên khoá cũ hơn 30s bị coi là của process đã
// chết và bị dọn (một lệnh pp thật chạy dưới 1 giây; giữ khoá 30s nghĩa là đã
// chết). Hết `PP_LOCK_TIMEOUT_MS` (mặc định 5s — seam cho test, không phải nút
// chỉnh cho người dùng) thì lỗi to, nói rõ đường khoá và lối ra.
const LOCK_DIR = '.pp-lock'
const LOCK_STALE_MS = 30_000

// Ngủ đồng bộ không đốt CPU: Atomics.wait chặn thread hiện tại đúng ms mili-giây
// (giá trị tại index 0 là 0 nên "chờ đổi giá trị" luôn hết hạn theo timeout).
function sleepMs(ms) {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms)
}

export function withStateLock(featureDir, fn) {
  const lock = join(featureDir, LOCK_DIR)
  const timeout = Number(process.env.PP_LOCK_TIMEOUT_MS) > 0 ? Number(process.env.PP_LOCK_TIMEOUT_MS) : 5000
  const deadline = Date.now() + timeout
  for (;;) {
    try {
      mkdirSync(lock)
      break
    } catch (err) {
      if (err.code !== 'EEXIST') throw err
      let mtime
      try {
        mtime = statSync(lock).mtimeMs
      } catch {
        continue // khoá vừa được nhả giữa hai lời gọi — thử giành lại ngay
      }
      if (Date.now() - mtime > LOCK_STALE_MS) {
        try { rmdirSync(lock) } catch { /* bên khác dọn trước — vòng sau giành */ }
        continue
      }
      if (Date.now() >= deadline) {
        throw new Error(
          `không giành được khoá ${lock} sau ${timeout}ms — một lệnh pp khác đang ghi state của feature này.\n` +
          'Chờ nó xong rồi chạy lại. Nếu chắc chắn không còn lệnh pp nào chạy (khoá của một process đã chết ' +
          `dưới 30 giây trước), xoá thư mục khoá đó rồi thử lại.`,
        )
      }
      sleepMs(25)
    }
  }
  try {
    return fn()
  } finally {
    try { rmdirSync(lock) } catch { /* đã bị bên khác coi là stale và dọn — không còn gì để nhả */ }
  }
}

export function hashInputs(featureDir, inputs) {
  const h = createHash('sha256')
  for (const inp of inputs) {
    const p = join(featureDir, inp.path)
    if (!existsSync(p)) {
      if (inp.optional) continue
      throw new Error(`input bắt buộc không tồn tại: ${inp.path}`)
    }
    h.update(inp.path).update('\0').update(readFileSync(p))
  }
  return h.digest('hex').slice(0, 6)
}

// R1 (review cuối) — MỘT KẾT QUẢ TIER CHỈ CÓ GIÁ TRỊ VỚI ĐÚNG ARTIFACT NÓ
// ĐÃ CHẤM. `isStale` chỉ băm INPUT thượng nguồn của stage, không bao giờ băm
// chính OUTPUT của nó — nên một stage đã `done` hợp lệ vẫn giữ nguyên `done`
// sau khi artifact bị viết lại thành nội dung khác hẳn (quan sát được: PRD
// bị sửa thành "bỏ hoàn toàn kiểm tra phân quyền" mà `pp gate` vẫn in
// "✓ done"). T2 không chạy lại; phán quyết cũ được ghi cho BẢN TRƯỚC.
//
// Dùng lại CHÍNH cách băm của `hashInputs` (sha256 trên path + nội dung, cắt
// 6 hex) — một cách băm duy nhất trong toàn hệ, không đẻ ra cách thứ hai.
export function hashArtifact(featureDir, path) {
  try {
    return hashInputs(featureDir, [{ path, optional: false }])
  } catch {
    // Artifact được khai báo nhưng không còn trên đĩa: không băm được, và
    // cũng không được coi là "khớp" với bất kỳ hash nào đã ghi.
    return 'missing'
  }
}

export function isStale(featureDir, config, state, stageId) {
  const st = state.stages?.[stageId]
  if (st?.status !== 'done') return false
  // Overridden stages are never stale (override is an explicit human decision)
  if (st.overridden) return false
  // If no hash recorded, stage is stale (unknown provenance — re-gate)
  if (!st.inputs_hash) return true
  return hashInputs(featureDir, config.stages[stageId].inputs) !== st.inputs_hash
}

// `isStale` gọi `hashInputs`, hàm này NÉM khi một input bắt buộc không còn trên
// đĩa — nên mọi chỗ hỏi "stage này còn tươi không" trên dữ liệu THẬT đều phải bọc
// nó lại. Không băm được = không chứng minh được là còn tươi = coi như đã đổi,
// cùng chiều bảo thủ mà `isStale` áp cho `inputs_hash` vắng mặt.
//
// B6: bản đầu tiên của phép bọc này nằm trong `lib/commands/report.js` (hàm
// `upstreamChanged`) và CHỈ report dùng — nên `pp approve` duyệt được đúng cái
// stage mà `pp status` đang báo `regate`. Đưa lên đây để hai lệnh không thể trả
// lời khác nhau về cùng một stage.
export function staleOrUnverifiable(featureDir, config, state, stageId) {
  try {
    return isStale(featureDir, config, state, stageId)
  } catch {
    return true
  }
}
