import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { join } from 'node:path'

const FILE = 'STATE.md'
const OPEN = '<!-- pp:state'
const CLOSE = '-->'

export function readState(featureDir) {
  const file = join(featureDir, FILE)
  if (!existsSync(file)) return { feature: null, current: null, stages: {} }
  const txt = readFileSync(file, 'utf8')
  const i = txt.indexOf(OPEN)
  if (i === -1) throw new Error(`${file}: thiếu khối ${OPEN} — file có thể đã bị sửa tay`)
  const j = txt.indexOf(CLOSE, i)
  const json = txt.slice(i + OPEN.length, j).trim()
  return JSON.parse(json)
}

function renderTable(state) {
  const head = '| stage | status | attempts | gate | human |\n|---|---|---|---|---|'
  const rows = Object.entries(state.stages).map(
    ([id, s]) =>
      `| ${id} | ${s.status ?? 'pending'} | ${s.attempts ?? 0} | ${s.gate ?? '-'} | ${s.human ?? '-'} |`,
  )
  return [head, ...rows].join('\n')
}

export function writeState(featureDir, state) {
  const body = `<!-- GENERATED BY pp — DO NOT EDIT (PreToolUse hook chặn agent ghi file này) -->
# STATE — ${state.feature ?? ''}

current: **${state.current ?? '(hoàn tất)'}** · updated: ${state.updated ?? new Date().toISOString()}

${renderTable(state)}

${OPEN}
${JSON.stringify({ ...state, updated: state.updated ?? new Date().toISOString() }, null, 2)}
${CLOSE}
`
  writeFileSync(join(featureDir, FILE), body)
}

export function hashInputs(featureDir, inputs) {
  const h = createHash('sha256')
  for (const inp of inputs) {
    const p = join(featureDir, inp.path)
    if (!existsSync(p)) {
      if (inp.optional) continue
      throw new Error(`input bắt buộc không tồn tại: ${inp.path}`)
    }
    h.update(inp.path).update('\0').update(readFileSync(p))
  }
  return h.digest('hex').slice(0, 6)
}

export function isStale(featureDir, config, state, stageId) {
  const st = state.stages?.[stageId]
  if (!st || st.status !== 'done' || !st.inputs_hash) return false
  return hashInputs(featureDir, config.stages[stageId].inputs) !== st.inputs_hash
}
